development:
  openai:
    api_key: <%= ENV['OPENAI_API_KEY'] %>
    organization_id: <%= ENV['OPENAI_ORGANIZATION_ID'] %>
  grok:
    api_key: <%= ENV['XAI_API_KEY'] %>
  google_app_name: <%= ENV['GMAIL_USERNAME'] %>
  google_app_password: <%= ENV['GMAIL_APP_PASSWORD'] %>
  google_oauth_client_id: <%= ENV['GOOGLE_OAUTH_CLIENT_ID'] %>
  google_oauth_client_secret: <%= ENV['GOOGLE_OAUTH_CLIENT_SECRET'] %>
  twitter_api_key: <%= ENV['TWITTER_API_KEY'] %>
  twitter_api_secret: <%= ENV['TWITTER_API_SECRET'] %>

production:
  openai:
    api_key: <%= ENV['OPENAI_API_KEY'] %>
    organization_id: <%= ENV['OPENAI_ORGANIZATION_ID'] %>
  grok:
    api_key: <%= ENV['XAI_API_KEY'] %>
  domain: <%= ENV['DOMAIN_NAME'] %>
  google_app_name: <%= ENV['GMAIL_USERNAME'] %>
  google_app_password: <%= ENV['GMAIL_APP_PASSWORD'] %>
  google_oauth_client_id: <%= ENV['GOOGLE_OAUTH_CLIENT_ID'] %>
  google_oauth_client_secret: <%= ENV['GOOGLE_OAUTH_CLIENT_SECRET'] %>
  twitter_api_key: <%= ENV['TWITTER_API_KEY'] %>
  twitter_api_secret: <%= ENV['TWITTER_API_SECRET'] %>